# Generated by Django 6.0.1 on 2026-02-18 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_clinic_doctor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('clinic_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('role', models.CharField(default='clinic_doctor', max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinic_doctor_images/')),
                ('medical_id', models.ImageField(blank=True, null=True, upload_to='clinic_medical_ids/')),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_hospital_doctor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_address', models.TextField(blank=True, null=True)),
                ('hospital_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('role', models.CharField(default='hospital_doctor', max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospital_doctor_images/')),
                ('medical_id', models.ImageField(blank=True, null=True, upload_to='hospital_medical_ids/')),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicDoctorTimeSlotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timeslots', models.JSONField(blank=True, default=list)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_groups', to='medicoapp.tbl_clinic_doctor_register')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDoctorTimeSlotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timeslots', models.JSONField(blank=True, default=list)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_groups', to='medicoapp.tbl_hospital_doctor_register')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDoctorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_feedbacks', to='medicoapp.tbl_hospital_doctor_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_feedbacks', to='medicoapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(default='booked', max_length=20)),
                ('is_booked', models.BooleanField(default=True)),
                ('timeslot_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.hospitaldoctortimeslotgroup')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicoapp.tbl_hospital_doctor_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicDoctorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.tbl_clinic_doctor_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeslot_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbookings', to='medicoapp.clinicdoctortimeslotgroup')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbookings', to='medicoapp.tbl_clinic_doctor_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_bookings1', to='medicoapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('q1_answer', models.TextField(blank=True, null=True)),
                ('q2_answer', models.TextField(blank=True, null=True)),
                ('q3_answer', models.TextField(blank=True, null=True)),
                ('q4_answer', models.TextField(blank=True, null=True)),
                ('q5_answer', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.TextField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('asked_remedy', models.BooleanField(default=False)),
                ('given_remedy', models.BooleanField(default=False)),
                ('remedy_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.tbl_register')),
            ],
        ),
    ]
