# Generated by Django 5.1.7 on 2025-07-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
