# Generated by Django 5.1.7 on 2025-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0002_tbl_register_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('role', models.CharField(default='doctor', max_length=20)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('house', 'House'), ('clinic', 'Clinic')], default='house', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('medical_id', models.ImageField(blank=True, null=True, upload_to='medical_ids/')),
            ],
        ),
    ]
