# Generated by Django 5.1.7 on 2025-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0003_tbl_doctor_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor_register',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
