# Generated by Django 5.1.7 on 2025-07-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0004_tbl_doctor_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor_register',
            name='hospital_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
