# Generated by Django 5.1.7 on 2025-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0005_tbl_doctor_register_hospital_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor_register',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
