# Generated by Django 5.1.7 on 2025-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0006_alter_tbl_doctor_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor_register',
            name='category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic')], default='house', max_length=20),
        ),
    ]
