# Generated by Django 5.1.7 on 2025-08-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0007_alter_tbl_doctor_register_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor_register',
            name='category',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic')], default='clinic', max_length=20),
        ),
        migrations.CreateModel(
            name='HealthChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('q1_answer', models.TextField(blank=True, null=True)),
                ('q2_answer', models.TextField(blank=True, null=True)),
                ('q3_answer', models.TextField(blank=True, null=True)),
                ('q4_answer', models.TextField(blank=True, null=True)),
                ('q5_answer', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.tbl_register')),
            ],
        ),
    ]
