# Generated by Django 5.1.7 on 2025-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0008_alter_tbl_doctor_register_category_healthchatsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthchatsession',
            name='predicted_disease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
