# Generated by Django 5.1.7 on 2025-08-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0009_alter_healthchatsession_predicted_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('q1_answer', models.TextField(blank=True, null=True)),
                ('q2_answer', models.TextField(blank=True, null=True)),
                ('q3_answer', models.TextField(blank=True, null=True)),
                ('q4_answer', models.TextField(blank=True, null=True)),
                ('q5_answer', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.TextField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('asked_remedy', models.BooleanField(default=False)),
                ('given_remedy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicoapp.tbl_register')),
            ],
        ),
    ]
