# Generated by Django 5.1.7 on 2025-08-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0010_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='remedy_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
