# Generated by Django 5.1.7 on 2025-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoapp', '0012_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='day_of_week',
            new_name='end_day',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
