# Generated by Django 5.1.7 on 2025-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0013_rename_day_of_week_timeslot_end_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_doctor_register",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
