# Generated by Django 5.1.7 on 2025-10-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0014_tbl_doctor_register_available"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Timeslot",
        ),
    ]
