# Generated by Django 5.1.7 on 2025-10-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0015_delete_timeslot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HealthChatSession",
        ),
    ]
