# Generated by Django 5.1.7 on 2025-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0017_tbl_clinic_doctor_register_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_clinic_doctor_register",
            name="role",
            field=models.CharField(default="clinic_doctor", max_length=30),
        ),
        migrations.AlterField(
            model_name="tbl_hospital_doctor_register",
            name="role",
            field=models.CharField(default="hospital_doctor", max_length=30),
        ),
    ]
