# Generated by Django 5.1.7 on 2025-10-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0018_alter_tbl_clinic_doctor_register_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_clinic_doctor_register",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="clinic_doctor_images/"
            ),
        ),
        migrations.AlterField(
            model_name="tbl_clinic_doctor_register",
            name="medical_id",
            field=models.ImageField(
                blank=True, null=True, upload_to="clinic_medical_ids/"
            ),
        ),
        migrations.AlterField(
            model_name="tbl_hospital_doctor_register",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hospital_doctor_images/"
            ),
        ),
        migrations.AlterField(
            model_name="tbl_hospital_doctor_register",
            name="medical_id",
            field=models.ImageField(
                blank=True, null=True, upload_to="hospital_medical_ids/"
            ),
        ),
    ]
