# Generated by Django 5.1.7 on 2025-10-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0019_alter_tbl_clinic_doctor_register_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicDoctorTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to="medicoapp.tbl_clinic_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to="medicoapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
    ]
