# Generated by Django 5.1.7 on 2025-10-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0020_clinicdoctortimeslot_hospitaldoctortimeslot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitaldoctortimeslot",
            name="doctor",
        ),
        migrations.CreateModel(
            name="ClinicDoctorTimeSlotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_groups",
                        to="medicoapp.tbl_clinic_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicDoctorSubSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subslots",
                        to="medicoapp.clinicdoctortimeslotgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorTimeSlotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_groups",
                        to="medicoapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorSubSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subslots",
                        to="medicoapp.hospitaldoctortimeslotgroup",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ClinicDoctorTimeSlot",
        ),
        migrations.DeleteModel(
            name="HospitalDoctorTimeSlot",
        ),
    ]
