# Generated by Django 5.1.7 on 2025-10-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0021_remove_hospitaldoctortimeslot_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicdoctortimeslotgroup",
            name="timeslots",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="ClinicDoctorSubSlot",
        ),
    ]
