# Generated by Django 5.1.7 on 2025-10-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0022_clinicdoctortimeslotgroup_timeslots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitaldoctortimeslotgroup",
            name="timeslots",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="HospitalDoctorSubSlot",
        ),
    ]
