# Generated by Django 5.1.7 on 2025-10-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0023_hospitaldoctortimeslotgroup_timeslots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_clinic_doctor_register",
            name="clinic_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tbl_hospital_doctor_register",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
