# Generated by Django 5.1.7 on 2025-11-01 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0025_clinicdoctorbooking_hospitaldoctorbooking_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=10)),
                ("is_booked", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbookings",
                        to="medicoapp.tbl_clinic_doctor_register",
                    ),
                ),
                (
                    "timeslot_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbookings",
                        to="medicoapp.clinicdoctortimeslotgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_bookings1",
                        to="medicoapp.tbl_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=20)),
                ("status", models.CharField(default="booked", max_length=20)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicoapp.tbl_hospital_doctor_register",
                    ),
                ),
                (
                    "timeslot_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicoapp.hospitaldoctortimeslotgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicoapp.tbl_register",
                    ),
                ),
            ],
        ),
    ]
