# Generated by Django 5.1.7 on 2025-11-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0026_clinicbooking_hospitalbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicbooking",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cbookings",
                to="medicoapp.tbl_clinic_doctor_register",
            ),
        ),
        migrations.AlterField(
            model_name="hospitalbooking",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicoapp.tbl_hospital_doctor_register",
            ),
        ),
    ]
