# Generated by Django 5.1.7 on 2025-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicoapp", "0027_alter_clinicbooking_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalbooking",
            name="is_booked",
            field=models.BooleanField(default=True),
        ),
    ]
